{{- if not .Values.odysseus.secrets.existingSecret -}}
{{- $s := .Values.odysseus.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odysseus.app.secretName" . }}
  labels:
    {{- include "odysseus.labels" . | nindent 4 }}
    app.kubernetes.io/component: odysseus
type: Opaque
stringData:
  {{- range $k, $v := $s }}
  {{- if and (ne $k "existingSecret") $v }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
{{- end }}
