{{- if and .Values.secretEnv.create (not .Values.secretEnv.existingSecret) .Values.secretEnv.values -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odysseus.secretName" . }}
  labels:
    {{- include "odysseus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv.values }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
