#!/bin/bash
set -e

# ═══════════════════════════════════════════════════════════════════════
#  Odysseus — Self-Contained macOS App Builder
#  Builds a standalone .app that bundles the Python server + Electron UI
# ═══════════════════════════════════════════════════════════════════════

cd "$(dirname "$0")"
PROJECT_DIR="$(pwd)"
ELECTRON_DIR="$PROJECT_DIR/electron-app"
BUILD_DIR="$ELECTRON_DIR/build"
DIST_DIR="$PROJECT_DIR/dist"
SERVER_BUILD_DIR="$PROJECT_DIR/server-build"

echo "═══════════════════════════════════════════════════════"
echo "  Odysseus Self-Contained App Builder"
echo "═══════════════════════════════════════════════════════"
echo "Project:  $PROJECT_DIR"
echo ""

# ── Step 0: Pre-flight checks ─────────────────────────────────────────
echo "▶ Step 0: Pre-flight checks"

if [[ ! -f "$PROJECT_DIR/app.py" ]]; then
    echo "  ✗ app.py not found in $PROJECT_DIR"
    exit 1
fi
echo "  ✓ app.py found"

if [[ ! -f "$PROJECT_DIR/server_entry.py" ]]; then
    echo "  ✗ server_entry.py not found — needed for PyInstaller build"
    exit 1
fi
echo "  ✓ server_entry.py found"

if [[ ! -d "$PROJECT_DIR/venv" ]]; then
    echo "  ✗ venv not found — run: python3 -m venv venv && venv/bin/pip install -r requirements.txt"
    exit 1
fi
echo "  ✓ venv exists"

if [[ ! -f "$ELECTRON_DIR/main.js" ]]; then
    echo "  ✗ $ELECTRON_DIR/main.js not found"
    echo "     The electron-app/ directory is missing required source files."
    echo "     It cannot be regenerated by this script; restore it from git or a backup."
    exit 1
fi
echo "  ✓ main.js found"

if [[ ! -f "$ELECTRON_DIR/preload.js" ]]; then
    echo "  ✗ $ELECTRON_DIR/preload.js not found"
    echo "     The electron-app/ directory is missing required source files."
    echo "     It cannot be regenerated by this script; restore it from git or a backup."
    exit 1
fi
echo "  ✓ preload.js found"

# ── Step 1: Build Python server with PyInstaller ──────────────────────
echo ""
echo "▶ Step 1: Build Python server (PyInstaller)"

# Clean previous build
rm -rf "$SERVER_BUILD_DIR"
mkdir -p "$SERVER_BUILD_DIR"

# IMPORTANT: Do NOT pass project .py files as PyInstaller scripts.
# Passing them as scripts flattens the package layout (core/session_manager.py
# becomes a top-level "session_manager" module) and breaks relative imports
# like `from .database import ...`. Instead, bundle each package directory via
# --add-data so the package structure is preserved inside the bundle, and rely
# on the project root being on sys.path (server_entry.py lives there) so the
# imports `from core...`, `from src...`, etc. resolve at runtime.

# Collect data directories the app needs at runtime (templates, static, data…)
DATA_DIRS=""
for dir in templates static data skills; do
    if [[ -d "$PROJECT_DIR/$dir" ]]; then
        DATA_DIRS="$DATA_DIRS --add-data $PROJECT_DIR/$dir:$dir"
    fi
done

# Remove stale build artifacts and accidental recursive repo copies that may
# have been created inside the repo data/ tree during earlier packaging attempts.
# They bloat the bundle and can confuse electron-builder.
rm -f "$PROJECT_DIR/data/odysseus/dist/Odysseus.dmg" \
      "$PROJECT_DIR/data/odysseus/data/dist/Odysseus.dmg" 2>/dev/null || true
if [[ -d "$PROJECT_DIR/data/odysseus" ]]; then
    # This is a recursive copy of the whole repo inside data/ — not needed.
    echo "  ⚠ Removing accidental repo copy inside data/odysseus/ (~786 MB)"
    rm -rf "$PROJECT_DIR/data/odysseus"
fi
if [[ -d "$PROJECT_DIR/data/.odysseus-app-data" ]]; then
    # Chromium/Electron profile data; created at runtime, should not be bundled.
    echo "  ⚠ Removing bundled Chromium profile data (~90 MB)"
    rm -rf "$PROJECT_DIR/data/.odysseus-app-data"
fi

# Bundle the local Python packages so their source is available inside the
# frozen app. Each is mapped to the same directory name at the bundle root,
# which keeps `from core...`, `from src...`, `from services...` working.
PKG_DIRS=""
for pkg in core src services routes mcp_servers companion integrations; do
    if [[ -d "$PROJECT_DIR/$pkg" ]]; then
        PKG_DIRS="$PKG_DIRS --add-data $PROJECT_DIR/$pkg:$pkg"
    fi
done

# Hidden imports for third-party libs used at runtime
HIDDEN_IMPORTS=(
    --hidden-import uvicorn
    --hidden-import uvicorn.logging
    --hidden-import uvicorn.loops
    --hidden-import uvicorn.loops.auto
    --hidden-import uvicorn.protocols
    --hidden-import uvicorn.protocols.http
    --hidden-import uvicorn.protocols.http.auto
    --hidden-import uvicorn.protocols.websockets
    --hidden-import uvicorn.protocols.websockets.auto
    --hidden-import uvicorn.lifespan
    --hidden-import uvicorn.lifespan.on
    --hidden-import fastapi
    --hidden-import gradio
    --hidden-import chromadb
    --hidden-import sentence_transformers
    --hidden-import sklearn
    --hidden-import sklearn.feature_extraction.text
    --hidden-import sklearn.metrics.pairwise
    --hidden-import bcrypt
)

# Run PyInstaller. Only server_entry.py is a script; packages are bundled
# via --add-data and discovered at runtime through sys.path (project root).
venv/bin/python3 -m PyInstaller \
    --noconfirm \
    --clean \
    --distpath "$SERVER_BUILD_DIR" \
    --workpath "$PROJECT_DIR/build-py" \
    --name odysseus-server \
    --onedir \
    $DATA_DIRS \
    $PKG_DIRS \
    "${HIDDEN_IMPORTS[@]}" \
    --collect-all gradio \
    --collect-all chromadb \
    --collect-all sentence_transformers \
    "$PROJECT_DIR/server_entry.py" \
    2>&1 | tail -40

if [[ ! -f "$SERVER_BUILD_DIR/odysseus-server/odysseus-server" ]]; then
    echo "  ✗ PyInstaller build failed — server binary not found"
    exit 1
fi
echo "  ✓ Python server built: $SERVER_BUILD_DIR/odysseus-server/odysseus-server"

# ── Step 2: Build icon ─────────────────────────────────────────────────
echo ""
echo "▶ Step 2: Build icon"

ICONSET_DIR="$BUILD_DIR/icon.iconset"
rm -rf "$ICONSET_DIR"
mkdir -p "$ICONSET_DIR"

ICON_SOURCE="$PROJECT_DIR/docs/odysseus.jpg"
if [[ ! -f "$ICON_SOURCE" ]]; then
    # Try other locations
    for src in "$PROJECT_DIR/docs/odysseus.png" "$PROJECT_DIR/odysseus.jpg" "$PROJECT_DIR/odysseus.png" "$PROJECT_DIR/icon.png"; do
        if [[ -f "$src" ]]; then
            ICON_SOURCE="$src"
            break
        fi
    done
fi

if [[ -f "$ICON_SOURCE" ]]; then
    echo "  Using icon source: $ICON_SOURCE"
    # sips keeps the source format unless we force a real PNG. Convert to a
    # real 1024x1024 PNG first (crop to square, then resize) so iconutil accepts it.
    ICONSET_DIR="$BUILD_DIR/icon.iconset"
    rm -rf "$ICONSET_DIR"
    mkdir -p "$ICONSET_DIR"
    # Determine source dimensions and crop to a centered square
    SRC_W=$(sips -g pixelWidth "$ICON_SOURCE" 2>/dev/null | awk '/pixelWidth/ {print $2}')
    SRC_H=$(sips -g pixelHeight "$ICON_SOURCE" 2>/dev/null | awk '/pixelHeight/ {print $2}')
    CROP=${SRC_H}
    (( SRC_W < SRC_H )) && CROP=${SRC_W}
    SQUARE_PNG="$BUILD_DIR/icon_square.png"
    sips -c "$CROP" "$CROP" "$ICON_SOURCE" --out "$SQUARE_PNG" >/dev/null 2>&1 || true
    sips -s format png -z 1024 1024 "$SQUARE_PNG" --out "$SQUARE_PNG" >/dev/null 2>&1 || true
    for spec in \
      "icon_16x16.png 16" \
      "icon_16x16@2x.png 32" \
      "icon_32x32.png 32" \
      "icon_32x32@2x.png 64" \
      "icon_128x128.png 128" \
      "icon_128x128@2x.png 256" \
      "icon_256x256.png 256" \
      "icon_256x256@2x.png 512" \
      "icon_512x512.png 512" \
      "icon_512x512@2x.png 1024"; do
        name="${spec%% *}"
        size="${spec##* }"
        sips -s format png -z "$size" "$size" "$SQUARE_PNG" --out "$ICONSET_DIR/$name" >/dev/null 2>&1 || true
    done
    iconutil -c icns "$ICONSET_DIR" -o "$BUILD_DIR/icon.icns" 2>&1 || true
    # Also keep a 1024x1024 PNG version for the window icon (electron-builder
    # requires icon.png to be at least 512x512).
    sips -s format png -z 1024 1024 "$SQUARE_PNG" --out "$BUILD_DIR/icon.png" >/dev/null 2>&1 || true
    rm -f "$SQUARE_PNG"
    echo "  ✓ Icon built"
else
    echo "  ⚠ No icon source found, using default"
fi

# Copy the Odysseus wordmark into the build directory so the loading screen
# can use real branding instead of a generic emoji. The source PNG has a
# transparent background, so it renders correctly on both light and dark themes.
WORDMARK_SOURCE="$PROJECT_DIR/docs/odysseus-wordmark.png"
if [[ -f "$WORDMARK_SOURCE" ]]; then
    cp "$WORDMARK_SOURCE" "$BUILD_DIR/odysseus-wordmark.png"
    echo "  ✓ Wordmark copied"
else
    echo "  ⚠ No wordmark source found"
fi

# ── Step 3: Copy server into Electron resources ───────────────────────
echo ""
echo "▶ Step 3: Copy server into Electron build dir"

SERVER_TARGET="$ELECTRON_DIR/build/server"
rm -rf "$SERVER_TARGET"
mkdir -p "$SERVER_TARGET"
cp -R "$SERVER_BUILD_DIR/odysseus-server/"* "$SERVER_TARGET/"
echo "  ✓ Server copied to $SERVER_TARGET"
du -sh "$SERVER_TARGET" 2>/dev/null

# ── Step 4: Update package.json ────────────────────────────────────────
echo ""
echo "▶ Step 4: Update package.json"

# Make sure icon is .icns and extraResources includes the server
cat > "$ELECTRON_DIR/package.json" << 'PKGJSON'
{
  "name": "odysseus",
  "version": "1.0.0",
  "description": "Self-contained Odysseus app",
  "main": "main.js",
  "author": "Odysseus",
  "license": "MIT",
  "scripts": {
    "start": "electron .",
    "build": "electron-builder --mac",
    "build:signed": "electron-builder --mac --config.mac.identity=builder --config.mac.hardenedRuntime=true",
    "dev": "NODE_ENV=development electron ."
  },
  "devDependencies": {
    "electron": "^28.0.0",
    "electron-builder": "^24.9.1"
  },
  "build": {
    "appId": "com.odysseus.app",
    "productName": "Odysseus",
    "directories": {
      "output": "../dist-electron",
      "buildResources": "build"
    },
    "files": [
      "main.js",
      "preload.js",
      "entitlements.plist",
      "notarize.js",
      "build/icon.png",
      "build/icon.icns"
    ],
    "extraResources": [
      {
        "from": "build/server",
        "to": "server",
        "filter": ["**/*"]
      },
      {
        "from": "../data",
        "to": "data",
        "filter": ["**/*"]
      },
      {
        "from": "build/icon.png",
        "to": "icon.png"
      },
      {
        "from": "build/odysseus-wordmark.png",
        "to": "odysseus-wordmark.png"
      }
    ],
    "mac": {
      "category": "public.app-category.productivity",
      "target": [
        {
          "target": "dir",
          "arch": ["arm64"]
        },
        {
          "target": "dmg",
          "arch": ["arm64"]
        }
      ],
      "icon": "build/icon.icns",
      "hardenedRuntime": false,
      "gatekeeperAssess": false,
      "identity": null,
      "entitlements": "entitlements.plist",
      "entitlementsInherit": "entitlements.plist"
    },
    "afterSign": "notarize.js"
  }
}
PKGJSON

echo "  ✓ package.json updated"

# ── Step 5: Build Electron app ─────────────────────────────────────────
echo ""
echo "▶ Step 5: Build Electron app"

cd "$ELECTRON_DIR"

# Install deps if needed
if [[ ! -d node_modules ]]; then
    echo "  Installing npm dependencies…"
    npm install 2>&1 | tail -5
fi

# Build
npx electron-builder --mac 2>&1 | tail -20

# ── Step 6: Copy to dist ───────────────────────────────────────────────
echo ""
echo "▶ Step 6: Copy to dist"

cd "$PROJECT_DIR"
rm -rf "$DIST_DIR/Odysseus.app" "$DIST_DIR/Odysseus.dmg"

# Find the built app (could be mac-arm64 or mac)
for apppath in "dist-electron/mac-arm64/Odysseus.app" "dist-electron/mac/Odysseus.app" "dist-electron/mac-x64/Odysseus.app"; do
    if [[ -d "$apppath" ]]; then
        cp -R "$apppath" "$DIST_DIR/Odysseus.app"
        break
    fi
done

# Find the built dmg (could be mac-arm64 or mac)
for dmgpath in "dist-electron/Odysseus-1.0.0-arm64.dmg" "dist-electron/Odysseus-1.0.0.dmg" "dist-electron/mac-arm64/Odysseus-1.0.0-arm64.dmg" "dist-electron/mac/Odysseus-1.0.0.dmg"; do
    if [[ -f "$dmgpath" ]]; then
        cp "$dmgpath" "$DIST_DIR/Odysseus.dmg"
        break
    fi
done

if [[ ! -d "$DIST_DIR/Odysseus.app" ]]; then
    echo "  ✗ Build failed — no .app found in dist-electron/"
    ls -la dist-electron/ 2>/dev/null
    exit 1
fi

touch "$DIST_DIR/Odysseus.app"

echo "  ✓ App built: $DIST_DIR/Odysseus.app"
du -sh "$DIST_DIR/Odysseus.app" 2>/dev/null

if [[ -f "$DIST_DIR/Odysseus.dmg" ]]; then
    echo "  ✓ DMG built: $DIST_DIR/Odysseus.dmg"
    du -sh "$DIST_DIR/Odysseus.dmg" 2>/dev/null
else
    echo "  ⚠ DMG not found; .app is available for local use"
fi

# Verify the server binary is included
SERVER_IN_APP="$DIST_DIR/Odysseus.app/Contents/Resources/server/odysseus-server"
if [[ -f "$SERVER_IN_APP" ]]; then
    echo "  ✓ Server binary bundled in app"
else
    echo "  ⚠ Server binary NOT found in app bundle!"
    echo "    Expected: $SERVER_IN_APP"
    find "$DIST_DIR/Odysseus.app/Contents/Resources" -maxdepth 2 -type f | head -20
    exit 1
fi

# ── Step 7: Done ───────────────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════════════════"
echo "  ✓ Build complete!"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "  App: $DIST_DIR/Odysseus.app"
echo ""
echo "  To launch:"
echo "    open $DIST_DIR/Odysseus.app"
echo ""
echo "  The app is self-contained — it starts its own Python"
echo "  server on port 7860 automatically. No terminal needed."
