# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['installer.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('.env.example', '.'),
        ('app.py', '.'),
        ('core', 'core'),
        ('routes', 'routes'),
        ('src', 'src'),
        ('services', 'services'),
        ('config', 'config'),
        ('static', 'static'),
        ('mcp_servers', 'mcp_servers'),
        ('integrations', 'integrations'),
        ('companion', 'companion'),
        ('scripts', 'scripts'),
        ('connect-android-pc.bat', '.'),
        ('launch-windows.ps1', '.'),
        ('requirements.txt', '.'),
        ('setup.py', '.')
    ],
    hiddenimports=['win32com.client'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Odysseus_Setup',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    uac_admin=False,
)
