"""Default wizard draft — mirrors Fugassa II `_default_wizard_draft()`."""

from __future__ import annotations

from typing import Any

# WizardDnd5eOptions default indices: Human=16, Fighter=4 in race/class lists
_DEFAULT_RACE_IDX = 16
_DEFAULT_CLASS_IDX = 4


def default_wizard_draft() -> dict[str, Any]:
    return {
        "world_name": "New Campaign",
        "campaign_length": "medium",
        "theme_mode": "Fantasy",
        "theme_custom": "",
        "image_style": "",
        "world_information": "",
        "world_info_chat_history": [],
        "world_campaign_options_text": "",
        "world_options_next_start": 1,
        "world_campaign_batch_start": 1,
        "world_info_seed_generated": False,
        "world_info_locked": False,
        "player_name": "Hero",
        "player_gender_idx": 0,
        "player_gender_custom": "",
        "player_race_idx": _DEFAULT_RACE_IDX,
        "player_race_custom": "",
        "player_class_idx": _DEFAULT_CLASS_IDX,
        "player_class_custom": "",
        "player_subclass_idx": 0,
        "player_subclass_custom": "",
        "player_subrace_idx": 0,
        "player_subrace_custom": "",
        "player_age": "",
        "character_background": "",
        "backstory_options_next_start": 1,
        "backstory_options_batch_start": 1,
        "backstory_chat_history": [],
        "backstory_seed_generated": False,
        "backstory_locked": False,
        "level": 1,
        "abilities": {"str": 10, "dex": 10, "con": 10, "int": 10, "wis": 10, "cha": 10},
        "abilities_method": "point_buy",
        "abilities_roll_used": False,
        "inventory_notes": "",
        "inventory_chat_history": [],
        "inventory_options_raw": "",
        "inventory_options_next_start": 1,
        "inventory_options_batch_start": 1,
        "inventory_structured": {"items": []},
        "inventory_seed_generated": False,
        "start_weapon": "Basic Sword",
        "start_armor": "Cloth Vest",
        "gear_chat_history": [],
        "gear_options_raw": "",
        "gear_options_next_start": 1,
        "gear_options_batch_start": 1,
        "gear_structured": {"weapon": {}, "armor": {}},
        "gear_seed_generated": False,
        "opening_hook": "",
        "currency": ["bronze", "silver", "gold"],
        "opening_chat_history": [],
        "opening_structured": {
            "opening_text": "",
            "time_hint": "",
            "currency": ["bronze", "silver", "gold"],
        },
        "opening_options_raw": "",
        "opening_options_next_start": 1,
        "opening_options_batch_start": 1,
        "opening_seed_generated": False,
        "playstyle": "adventure",
        "playstyle_framework": "rules_based",
        "rules_mode": "5e-style",
        "homebrew_llm_template_pick": 0,
        "resolution_mode": "dice",
        "rules_playstyle_tutorial_seen": False,
        "gm_selected_guide": "gm_custom_1.txt",
        "gm_guides_map": {},
        "gm_guides_builtin": {},
        "gm_guides_notes": "",
        "unlocked_tab": 0,
        "character_portrait_path": "",
        "world_info_tutorial_seen": False,
        "backstory_tutorial_seen": False,
        "inventory_tutorial_seen": False,
        "gear_tutorial_seen": False,
        "opening_tutorial_seen": False,
        "picture_locked": False,
        "picture_tutorial_seen": False,
        "_wizard_picture_tab_v1": False,
        "portrait_appearance": {},
        "skill_proficiencies": {},
        "expertise": {},
        "selected_cantrips": [],
        "selected_spells_by_level": {},
        "asi_choices": {},
        "homebrew_choices": {},
        "class_mechanic_choices": {},
        "homebrew_details": {},
        "sheet_snapshot": {},
    }
