"""Issue #6079: a stale generated llama-server shim must not block native recovery.

Cookbook writes a `llama-server` shim into ~/bin when only the pip bindings
exist. That shim keeps satisfying `command -v llama-server` forever, so the
native build/recovery branch is skipped and every serve stays on the slow
`python -m llama_cpp.server` path even after a real native binary appears.

The runner now relinks ~/bin/llama-server to a real native binary when one
exists. Assertions here are behavioral (symlink targets, exit codes, stdout):
each test runs the shipped shell with bash against a temporary HOME.

Why the shipped lines are extracted from the route source instead of being
obtained by calling the generator (required note per tests/TESTING_STANDARD.md,
behavioral-first policy): the runner lines are assembled by a nested builder
inside `setup_cookbook_routes()` that needs a fully-formed `ServeRequest` plus
request/session context, so invoking it from a unit test would test a
re-construction of the inputs rather than the real emission point. Extracting
the literals that the runner actually appends - and executing them for real -
keeps the assertions behavioral while pinning exactly what ships, so the test
cannot drift from production.
"""
import ast
import os
import re
import shutil
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
ROUTES = REPO / "routes" / "cookbook_routes.py"
SHIM_MARKER = "Auto-generated by Odysseus Cookbook"

pytestmark = pytest.mark.skipif(
    shutil.which("bash") is None, reason="bash is required to exercise the runner lines"
)


def _shipped_shell_lines() -> list[str]:
    """Pull the #6079 block's shell text out of the shipped source."""
    src = ROUTES.read_text(encoding="utf-8")
    start = src.index("# Issue #6079")
    region = src[start:]
    lines: list[str] = []
    for m in re.finditer(r"runner_lines\.append\((.*)\)[ \t]*$", region, re.M):
        literal = ast.literal_eval(m.group(1))
        lines.append(literal)
        if literal == "fi":
            break
    assert lines, "no runner_lines found after the #6079 marker"
    assert lines[-1] == "fi", f"extraction stopped early: {lines[-1]!r}"
    return lines


def _run(home: Path) -> subprocess.CompletedProcess:
    env = {**os.environ, "HOME": str(home)}
    script = "\n".join(_shipped_shell_lines())
    return subprocess.run(["bash", "-c", script], env=env,
                          capture_output=True, text=True, check=False)


def _write(path: Path, content: str, executable: bool = True) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    if executable:
        path.chmod(0o755)


def _shim_body() -> str:
    return f"#!/usr/bin/env bash\n# {SHIM_MARKER}: a llama-server lookalike\nexec python3 -m llama_cpp.server\n"


def test_stale_shim_is_replaced_by_native_binary(tmp_path):
    """The core #6079 case: shim in ~/bin, real binary in ~/.local/bin."""
    _write(tmp_path / "bin" / "llama-server", _shim_body())
    native = tmp_path / ".local" / "bin" / "llama-server"
    _write(native, "#!/bin/sh\necho native\n")

    result = _run(tmp_path)

    assert result.returncode == 0, result.stderr
    target = tmp_path / "bin" / "llama-server"
    assert target.is_symlink(), "stale shim was not relinked to the native binary"
    assert target.resolve() == native.resolve()
    assert "relinked" in result.stdout


def test_shim_left_alone_when_no_native_binary_exists(tmp_path):
    """Fallback stays intact: nothing native -> the shim keeps working."""
    shim = tmp_path / "bin" / "llama-server"
    _write(shim, _shim_body())

    result = _run(tmp_path)

    assert result.returncode == 0, result.stderr
    assert not shim.is_symlink()
    assert SHIM_MARKER in shim.read_text(encoding="utf-8")
    assert "relinked" not in result.stdout


def test_existing_native_link_is_not_relinked_again(tmp_path):
    """Idempotent: a ~/bin entry already pointing at native is left alone."""
    native = tmp_path / ".local" / "bin" / "llama-server"
    _write(native, "#!/bin/sh\necho native\n")
    target = tmp_path / "bin" / "llama-server"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.symlink_to(native)

    result = _run(tmp_path)

    assert result.returncode == 0, result.stderr
    assert target.resolve() == native.resolve()
    assert "relinked" not in result.stdout


def test_another_shim_is_not_treated_as_native(tmp_path):
    """A shim copy elsewhere in the search path must not count as native."""
    _write(tmp_path / "bin" / "llama-server", _shim_body())
    _write(tmp_path / ".local" / "bin" / "llama-server", _shim_body())

    result = _run(tmp_path)

    assert result.returncode == 0, result.stderr
    assert not (tmp_path / "bin" / "llama-server").is_symlink()
    assert "relinked" not in result.stdout


def test_native_build_output_wins_over_other_candidates(tmp_path):
    """Precedence: a source build under ~/llama.cpp/build/bin is preferred."""
    build = tmp_path / "llama.cpp" / "build" / "bin" / "llama-server"
    _write(build, "#!/bin/sh\necho built\n")
    _write(tmp_path / ".local" / "bin" / "llama-server", "#!/bin/sh\necho local\n")
    _write(tmp_path / "bin" / "llama-server", _shim_body())

    result = _run(tmp_path)

    assert result.returncode == 0, result.stderr
    assert (tmp_path / "bin" / "llama-server").resolve() == build.resolve()