"""Agent loop package — split from agent_loop.py with legacy API compatibility."""

from src.agent_tools import FUNCTION_TOOL_SCHEMAS
from src.agent_loop._helpers import (
    _EXPLICIT_CONTINUATION_RE,
    _classify_agent_request,
    _detect_admin_intent,
    _endpoint_lookup_keys,
    _is_casual_low_signal,
    _is_explicit_continuation,
    _is_ollama_openai_compat_url,
    _normalize_stream_document_fences,
    _recent_context_for_retrieval,
    _strip_think_blocks,
)
from src.agent_loop._loop import (
    _append_tool_results,
    _compute_final_metrics,
    _detect_runaway_call,
    _empty_response_fallback,
    _resolve_tool_blocks,
    build_active_plan_note,
    stream_agent_loop,
)
from src.agent_loop._prompts import (
    TOOL_SECTIONS,
    _API_HOSTS,
    _DOMAIN_RULES,
    _DOMAIN_TOOL_MAP,
    _MCP_KEYWORDS,
    _assemble_prompt,
    _build_base_prompt,
    _build_system_prompt,
    _cached_base_prompt,
    _cached_base_prompt_key,
    _domain_rules_for_tools,
    get_builtin_overrides,
)

__all__ = [
    "FUNCTION_TOOL_SCHEMAS",
    "TOOL_SECTIONS",
    "_API_HOSTS",
    "_DOMAIN_RULES",
    "_DOMAIN_TOOL_MAP",
    "_EXPLICIT_CONTINUATION_RE",
    "_MCP_KEYWORDS",
    "_append_tool_results",
    "_assemble_prompt",
    "_build_base_prompt",
    "_build_system_prompt",
    "_cached_base_prompt",
    "_cached_base_prompt_key",
    "_classify_agent_request",
    "_compute_final_metrics",
    "_detect_admin_intent",
    "_detect_runaway_call",
    "_domain_rules_for_tools",
    "_empty_response_fallback",
    "_endpoint_lookup_keys",
    "_is_casual_low_signal",
    "_is_explicit_continuation",
    "_is_ollama_openai_compat_url",
    "_normalize_stream_document_fences",
    "_recent_context_for_retrieval",
    "_resolve_tool_blocks",
    "_strip_think_blocks",
    "build_active_plan_note",
    "get_builtin_overrides",
    "stream_agent_loop",
]
