"""Download routes for files generated by agent tools."""

import os
from pathlib import Path

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse

from src.artifacts import ARTIFACTS_DIR, artifact_dir_for_session, safe_session_id
from src.auth_helpers import get_current_user


def setup_artifact_routes(session_manager):
    router = APIRouter(prefix="/api/artifacts", tags=["artifacts"])

    def _inside(base: str, path: str) -> bool:
        base_real = os.path.realpath(base)
        path_real = os.path.realpath(path)
        try:
            return os.path.commonpath([base_real, path_real]) == base_real
        except ValueError:
            return False

    def _verify_artifact_owner(request: Request, session_id: str) -> None:
        sess = session_manager.get_session(session_id)
        if not sess:
            raise HTTPException(404, "Artifact not found")

        auth_mgr = getattr(request.app.state, "auth_manager", None)
        auth_configured = bool(auth_mgr and getattr(auth_mgr, "is_configured", False))
        if not auth_configured:
            return

        user = get_current_user(request)
        if not user:
            raise HTTPException(403, "Access denied")
        owner = getattr(sess, "owner", None)
        if owner == user:
            return
        if hasattr(auth_mgr, "is_admin") and auth_mgr.is_admin(user):
            return
        raise HTTPException(404, "Artifact not found")

    @router.get("/{session_id}/{artifact_path:path}")
    async def download_artifact(request: Request, session_id: str, artifact_path: str):
        sid = safe_session_id(session_id)
        if sid != session_id:
            raise HTTPException(400, "Invalid session id")
        if not artifact_path or artifact_path.startswith("/") or ".." in Path(artifact_path).parts:
            raise HTTPException(400, "Invalid artifact path")

        _verify_artifact_owner(request, sid)

        base = artifact_dir_for_session(sid)
        path = os.path.join(base, artifact_path)
        if not _inside(ARTIFACTS_DIR, path) or not _inside(base, path):
            raise HTTPException(403, "Access denied")
        if not os.path.isfile(path):
            raise HTTPException(404, "Artifact not found")

        return FileResponse(path, filename=os.path.basename(path))

    return router
