name: odysseus_desktop
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.1
  webview_win_floating: ^3.0.3
  window_manager: ^0.5.1
  process_run: ^1.2.4
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  http: ^1.6.0
  logger: ^2.7.0
  path: ^1.9.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/logo.png

