apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: odysseus
resources:
  - buildconfigs.yaml
  - serviceaccount.yaml
  - pvcs.yaml
  - chromadb.yaml
  - searxng.yaml
  - odysseus.yaml
