#!/usr/bin/env python3
"""Generate Odysseus inner and outer seccomp artifacts deterministically."""

from __future__ import annotations

import argparse
import ctypes
import ctypes.util
import hashlib
import json
import sys
from pathlib import Path
from typing import Any


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SOURCE = HERE / "moby-default.json"
POLICY = HERE / "policy.json"
GENERATED_HEADER = HERE / "generated_inner_policy.h"
OUTER_PROFILE = ROOT / "docker" / "seccomp" / "odysseus-bubblewrap.json"


def _load_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return value


def _verify_source(policy: dict[str, Any]) -> None:
    raw = SOURCE.read_bytes()
    # The GitHub blob has no final newline. The checked-in copy has the normal
    # repository newline, so provenance is verified against the blob bytes.
    upstream_bytes = raw[:-1] if raw.endswith(b"\n") else raw
    actual = hashlib.sha256(upstream_bytes).hexdigest()
    expected = policy["moby"]["upstream_sha256"]
    if actual != expected:
        raise ValueError(
            f"vendored Moby profile digest mismatch: {actual} != {expected}"
        )


def _block_applies(block: dict[str, Any], moby_arch: str) -> bool:
    includes = block.get("includes") or {}
    excludes = block.get("excludes") or {}
    # Capability-dependent rules describe the outer container authority, not
    # the cap-dropped payload. They are intentionally excluded from the inner
    # policy and represented only by explicit rules below when required.
    if includes.get("caps") or excludes.get("caps"):
        return False
    include_arches = set(includes.get("arches") or ())
    exclude_arches = set(excludes.get("arches") or ())
    if include_arches and moby_arch not in include_arches:
        return False
    return moby_arch not in exclude_arches


def _allowlist_for_arch(
    source: dict[str, Any],
    policy: dict[str, Any],
    moby_arch: str,
) -> list[str]:
    denied = set(policy["denied_syscalls"])
    conditional = set(policy["conditional_syscalls"])
    names: set[str] = set()
    for block in source["syscalls"]:
        if block.get("action") != "SCMP_ACT_ALLOW":
            continue
        if not _block_applies(block, moby_arch):
            continue
        if block.get("args"):
            # Argument-sensitive rules are rebuilt explicitly by the trusted
            # launcher; never flatten them into unconditional allows.
            continue
        names.update(str(name) for name in block.get("names") or ())
    return sorted(names - denied - conditional)


def _c_array(name: str, values: list[str]) -> str:
    lines = [f"static const char *const {name}[] = {{"]
    lines.extend(f'    "{value}",' for value in values)
    lines.append("};")
    lines.append(
        f"static const size_t {name}_COUNT = sizeof({name}) / sizeof({name}[0]);"
    )
    return "\n".join(lines)


def _render_header(source: dict[str, Any], policy: dict[str, Any]) -> str:
    provenance = policy["moby"]
    x86 = _allowlist_for_arch(source, policy, policy["target_arches"]["x86_64"])
    arm = _allowlist_for_arch(source, policy, policy["target_arches"]["aarch64"])
    return "\n".join(
        [
            "/* Generated by security/seccomp/generate.py; do not edit. */",
            f"/* Moby {provenance['commit']} {provenance['path']} */",
            "#ifndef ODYSSEUS_GENERATED_INNER_POLICY_H",
            "#define ODYSSEUS_GENERATED_INNER_POLICY_H",
            "",
            "#include <stddef.h>",
            "",
            _c_array("ODYSSEUS_ALLOWED_X86_64", x86),
            "",
            _c_array("ODYSSEUS_ALLOWED_AARCH64", arm),
            "",
            f"#define ODYSSEUS_CLONE_NAMESPACE_MASK {policy['clone_namespace_mask']}ULL",
            "",
            "#endif",
            "",
        ]
    )


def _render_outer(source: dict[str, Any], policy: dict[str, Any]) -> str:
    outer = json.loads(json.dumps(source))
    bubblewrap = policy["outer_bubblewrap"]
    outer["syscalls"].append(
        {
            "names": ["clone"],
            "action": "SCMP_ACT_ALLOW",
            "args": [
                {
                    "index": 0,
                    "value": bubblewrap["clone_flags"],
                    "op": "SCMP_CMP_EQ",
                }
            ],
            "comment": "Odysseus trusted Bubblewrap namespace bootstrap only",
        }
    )
    outer["syscalls"].append(
        {
            "names": sorted(bubblewrap["bootstrap_syscalls"]),
            "action": "SCMP_ACT_ALLOW",
            "comment": "Odysseus trusted Bubblewrap mount bootstrap; inner filter denies payload use",
        }
    )
    return json.dumps(outer, indent=2, sort_keys=False) + "\n"


def _load_libseccomp() -> ctypes.CDLL:
    library = ctypes.util.find_library("seccomp") or "libseccomp.so.2"
    try:
        lib = ctypes.CDLL(library)
    except OSError as exc:
        raise RuntimeError("libseccomp is required for architecture verification") from exc
    lib.seccomp_arch_resolve_name.argtypes = [ctypes.c_char_p]
    lib.seccomp_arch_resolve_name.restype = ctypes.c_uint32
    lib.seccomp_syscall_resolve_name_arch.argtypes = [ctypes.c_uint32, ctypes.c_char_p]
    lib.seccomp_syscall_resolve_name_arch.restype = ctypes.c_int
    return lib


def _verify_arches(policy: dict[str, Any]) -> None:
    lib = _load_libseccomp()
    # These names are either installed through explicit argument-sensitive
    # rules by the launcher or are required for its core execution path. The
    # pinned Moby allowlists can also contain newer syscall names that an older
    # build-host libseccomp does not know yet. The launcher safely skips those
    # names under default-deny, so they must not make artifact verification
    # depend on the build host's syscall table version.
    required = {
        "clone",
        "clone3",
        "execve",
        "ioctl",
        "openat",
        "personality",
        "seccomp",
        "socket",
        "socketpair",
    }
    for generated_arch in policy["target_arches"]:
        token = lib.seccomp_arch_resolve_name(generated_arch.encode("ascii"))
        if token == 0:
            raise RuntimeError(f"libseccomp does not recognize {generated_arch}")
        missing_required = {
            name
            for name in required
            if lib.seccomp_syscall_resolve_name_arch(
                token, name.encode("ascii")
            ) < 0
        }
        if missing_required:
            raise RuntimeError(
                f"libseccomp cannot resolve {generated_arch} syscalls: "
                + ", ".join(sorted(missing_required))
            )


def _check_or_write(path: Path, content: str, check: bool) -> bool:
    if check:
        return path.is_file() and path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--verify-arches", action="store_true")
    args = parser.parse_args()

    source = _load_json(SOURCE)
    policy = _load_json(POLICY)
    _verify_source(policy)
    if args.verify_arches:
        _verify_arches(policy)

    outputs = {
        GENERATED_HEADER: _render_header(source, policy),
        OUTER_PROFILE: _render_outer(source, policy),
    }
    stale = [
        str(path.relative_to(ROOT))
        for path, content in outputs.items()
        if not _check_or_write(path, content, args.check)
    ]
    if stale:
        print("generated seccomp artifacts are stale: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
