#!/usr/bin/env python3
"""Run a command on the Docker host via the Docker socket.

Mounts the host root filesystem into an ephemeral Arch Linux container
with host network/pid namespaces, so tools like pacman, systemctl, etc.
operate on the actual host.

Usage:
  host-exec <command> [args...]

Examples:
  host-exec pacman -Syu
  host-exec systemctl status sshd
  host-exec cat /etc/os-release
"""
import docker
import sys
import os


def main():
    client = docker.DockerClient(base_url='unix:///var/run/docker.sock')
    cmd = sys.argv[1:] if len(sys.argv) > 1 else ['sh']

    kwargs = dict(
        image='archlinux:latest',
        command=cmd,
        detach=False,
        remove=True,
        network_mode='host',
        pid_mode='host',
        privileged=True,
        volumes={'/': {'bind': '/host', 'mode': 'rw'}},
        working_dir='/host',
        environment={
            'HOST_ROOT': '/host',
            'PS1': '[host] \\w$ ',
        },
    )

    try:
        output = client.containers.run(**kwargs)
    except docker.errors.ImageNotFound:
        print('Pulling archlinux:latest...', file=sys.stderr)
        client.images.pull('archlinux:latest')
        output = client.containers.run(**kwargs)
    except docker.errors.ContainerError as e:
        if e.stderr:
            sys.stderr.buffer.write(
                e.stderr if isinstance(e.stderr, bytes) else e.stderr.encode()
            )
        sys.exit(e.exit_status)

    if output:
        sys.stdout.buffer.write(
            output if isinstance(output, bytes) else output.encode()
        )


if __name__ == '__main__':
    main()
