#!/usr/bin/env bash
# scripts/podman-setup.sh — Set up Odysseus with Podman.
#
# Usage:
#   scripts/podman-setup.sh                # setup and start Odysseus
#   scripts/podman-setup.sh --env-only     # just create .env, don't start
#   scripts/podman-setup.sh --help         # show this help
#
# Requires: podman (4.x), podman-compose

set -euo pipefail

# ─── output helpers ──────────────────────────────────────────────────────────
PASS=0; FAIL=0
_pass() { printf '\033[32m[PASS]\033[0m %s\n' "$*"; PASS=$((PASS + 1)); }
_fail() { printf '\033[31m[FAIL]\033[0m %s\n' "$*"; FAIL=$((FAIL + 1)); }
_info() { printf '\033[34m[INFO]\033[0m %s\n' "$*"; }
_warn() { printf '\033[33m[WARN]\033[0m %s\n' "$*"; }
_step() { printf '\033[36m[STEP]\033[0m %s\n' "$*"; }

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$SCRIPT_DIR"

# ─── arg parsing ─────────────────────────────────────────────────────────────
MODE="full"
for arg in "$@"; do
  case "$arg" in
    --help)    sed -n '2,10p' "$0"; exit 0 ;;
    --env-only) MODE="env" ;;
    *) _warn "Unknown flag: $arg"; exit 1 ;;
  esac
done

echo ""
_info "Odysseus Podman Setup"
_info "====================="
echo ""

# ─── 1. Check prerequisites ─────────────────────────────────────────────────
_step "1/5  Checking prerequisites..."

if command -v podman &>/dev/null; then
  ver="$(podman version --format '{{.Version}}' 2>/dev/null || podman version 2>&1 | head -1)"
  _pass "podman found: $ver"
else
  _fail "podman not found. Install: sudo apt install podman"
  exit 1
fi

if command -v podman-compose &>/dev/null; then
  _pass "podman-compose found: $(podman-compose version 2>&1 | head -1)"
else
  _fail "podman-compose not found. Install: pip install podman-compose"
  exit 1
fi

# Check podman socket (needed for podman-compose to manage containers)
if systemctl --user is-active podman.socket &>/dev/null; then
  _pass "podman.socket is active"
else
  _warn "podman.socket is inactive — starting it..."
  systemctl --user enable --now podman.socket 2>/dev/null || true
  if systemctl --user is-active podman.socket &>/dev/null; then
    _pass "podman.socket started"
  else
    _warn "podman.socket not started. Running rootless podman may still work."
  fi
fi

# Check cgroup v2 (recommended)
if [ -f /sys/fs/cgroup/cgroup.controllers ]; then
  _pass "cgroup v2 detected"
else
  _warn "cgroup v1 detected — podman-compose healthchecks may behave differently"
fi

# ─── 2. Create .env ──────────────────────────────────────────────────────────
_step "2/5  Configuring environment..."

ENV_FILE="$SCRIPT_DIR/.env"
if [ -f "$ENV_FILE" ]; then
  _pass ".env already exists at $ENV_FILE"
else
  _info "Creating .env from defaults..."
  cat > "$ENV_FILE" <<- ENVEOF
	# Odysseus — Podman Environment (generated by podman-setup.sh)
	LLM_HOST=localhost
	AUTH_ENABLED=true
	ODYSSEUS_ADMIN_USER=admin
	ODYSSEUS_ADMIN_PASSWORD=odysseus
	SECURE_COOKIES=false
	APP_BIND=127.0.0.1
	APP_PORT=7000
	SEARXNG_INSTANCE=http://searxng:8080
	CHROMADB_HOST=chromadb
	CHROMADB_PORT=8000
	NTFY_BASE_URL=http://localhost:8091
	PUID=$(id -u)
	PGID=$(id -g)
	CLEANUP_INTERVAL_HOURS=24
	ODYSSEUS_INPROCESS_POLLERS=1
	ODYSSEUS_INPROCESS_TASKS=1
	ENVEOF
  _pass ".env created"
  _warn "Change ODYSSEUS_ADMIN_PASSWORD in .env before exposing to a network!"
fi

# ─── 3. Create required directories ──────────────────────────────────────────
_step "3/5  Creating data directories..."

mkdir -p "$SCRIPT_DIR/data" "$SCRIPT_DIR/logs" "$SCRIPT_DIR/data/ssh" \
         "$SCRIPT_DIR/data/huggingface" "$SCRIPT_DIR/data/local"

# Ensure bind-mount dirs are writable by the PUID/PGID from .env
source "$ENV_FILE" 2>/dev/null || true
PUID="${PUID:-$(id -u)}"
PGID="${PGID:-$(id -g)}"
chown -R "$PUID:$PGID" "$SCRIPT_DIR/data" "$SCRIPT_DIR/logs" 2>/dev/null || true
_pass "Data directories ready (owner: $PUID:$PGID)"

# ─── 4. Check podman-compose config ──────────────────────────────────────────
_step "4/5  Validating compose configuration..."

COMPOSE_FILES="-f docker-compose.yml -f docker/podman.yml"

if [ -f "$ENV_FILE" ]; then
  set +e
  source_env=$(grep -E '^COMPOSE_FILE=' "$ENV_FILE" 2>/dev/null)
  set -e
fi

if podman-compose $COMPOSE_FILES --dry-run config &>/dev/null; then
  _pass "Compose configuration is valid"
else
  _fail "Compose configuration validation failed. Run: podman-compose $COMPOSE_FILES config"
  exit 1
fi

# ─── 5. GPU check ────────────────────────────────────────────────────────────
_step "5/5  Checking GPU access..."

GPU_AVAILABLE=0
if command -v nvidia-smi &>/dev/null || [ -d /proc/driver/nvidia ]; then
  _info "NVIDIA GPU detected on host."
  if podman info 2>/dev/null | grep -qi "nvidia"; then
    _pass "NVIDIA container toolkit configured for podman"
    GPU_AVAILABLE=1
  else
    _warn "NVIDIA GPU found but nvidia-container-toolkit not configured for podman."
    _warn "  Install: sudo nvidia-ctk runtime configure --runtime=podman && sudo systemctl restart podman"
    _info "  For GPU overlay: podman-compose -f docker-compose.yml -f docker/podman.yml -f docker/podman.gpu-nvidia.yml up -d"
  fi
fi

if [ -d /dev/dri ] && ls /dev/dri/render* &>/dev/null 2>&1; then
  _info "AMD/Intel GPU detected (/dev/dri present)."
  _info "  For AMD GPU overlay: podman-compose -f docker-compose.yml -f docker/podman.yml -f docker/gpu.amd.yml up -d"
  GPU_AVAILABLE=1
fi

if [ "$GPU_AVAILABLE" -eq 0 ]; then
  _info "No GPU detected — Odysseus will run in CPU mode."
fi

# ─── Summary ─────────────────────────────────────────────────────────────────
echo ""
_info "====================="
_info "Setup complete!"
echo ""
_info "Start Odysseus with Podman:"
_info "  podman-compose -f docker-compose.yml -f docker/podman.yml up -d"
echo ""
_info "View logs:"
_info "  podman-compose -f docker-compose.yml -f docker/podman.yml logs -f"
echo ""
_info "Stop:"
_info "  podman-compose -f docker-compose.yml -f docker/podman.yml down"
echo ""
_info "Open http://localhost:7000"
echo ""

if [ "$MODE" = "full" ]; then
  _step "Starting Odysseus via podman-compose..."
  exec podman-compose $COMPOSE_FILES up -d
fi
