"""Helpers for downloadable files generated by agent tools."""

from __future__ import annotations

import os
import re
from urllib.parse import quote
from pathlib import Path
from typing import Any

from src.constants import DATA_DIR


ARTIFACTS_DIR = os.path.join(DATA_DIR, "artifacts")

_DOWNLOADABLE_EXTS = {
    ".csv", ".doc", ".docx", ".html", ".json", ".md", ".ods", ".pdf",
    ".ppt", ".pptx", ".txt", ".xls", ".xlsm", ".xlsx", ".xml", ".zip",
}
_SESSION_RE = re.compile(r"^[A-Za-z0-9_-]{1,128}$")


def safe_session_id(session_id: str | None) -> str:
    sid = str(session_id or "default").strip()
    return sid if _SESSION_RE.fullmatch(sid) else "default"


def artifact_dir_for_session(session_id: str | None) -> str:
    path = os.path.join(ARTIFACTS_DIR, safe_session_id(session_id))
    os.makedirs(path, exist_ok=True)
    return path


def artifact_url_prefix(session_id: str | None) -> str:
    return f"/api/artifacts/{safe_session_id(session_id)}"


def _inside(base: str, path: str) -> bool:
    base_real = os.path.realpath(base)
    path_real = os.path.realpath(path)
    try:
        return os.path.commonpath([base_real, path_real]) == base_real
    except ValueError:
        return False


def snapshot_artifacts(session_id: str | None) -> set[str]:
    base = artifact_dir_for_session(session_id)
    found: set[str] = set()
    for root, _dirs, files in os.walk(base, followlinks=False):
        for name in files:
            path = os.path.join(root, name)
            if _inside(base, path):
                found.add(os.path.relpath(path, base))
    return found


def discover_new_artifacts(session_id: str | None, before: set[str] | None = None) -> list[dict[str, Any]]:
    base = artifact_dir_for_session(session_id)
    prefix = artifact_url_prefix(session_id)
    before = before or set()
    out: list[dict[str, Any]] = []
    for rel in sorted(snapshot_artifacts(session_id) - before):
        path = os.path.join(base, rel)
        if not _inside(base, path) or not os.path.isfile(path):
            continue
        ext = Path(rel).suffix.lower()
        if ext not in _DOWNLOADABLE_EXTS:
            continue
        name = os.path.basename(rel)
        url_rel = "/".join(
            quote(part, safe="")
            for part in rel.split(os.sep)
            if part and part != "."
        )
        out.append({
            "name": name,
            "path": path,
            "relative_path": url_rel,
            "url": f"{prefix}/{url_rel}",
            "size": os.path.getsize(path),
            "mime": _guess_artifact_mime(name),
        })
    return out


def _guess_artifact_mime(name: str) -> str:
    import mimetypes

    return mimetypes.guess_type(name)[0] or "application/octet-stream"
