use_default_settings: true

server:
  secret_key: "__SEARXNG_SECRET__"

search:
  formats:
    - html
    - json

engines:
  - name: radio browser
    disabled: true
  - name: ahmia
    disabled: true
  - name: torch
    disabled: true
